### ISSUE TITLE
Sending mail from docker container to external server with the same domain name

### ISSUE THREAD

**Issue by muzset** [MarvAmBass/docker-versatile-postfix#14]
Hello. I am using your docker image and everything works fine except one thing. I have a domain, mysite.com and i am using your docker image to **send** mail from this domain using my VDS. I also use an external mail service to **receive** mail to  mailboxes@mysite.com.  The service for **receiving**  mail is similar to google gsuite. Now, i want to send messages from my VDS to a mail service that is serving the same domain. When i send messages to mail@mysite.com from container the mail is not delivered. and i get following info in my docker logs

> Jan 31 22:12:57 be599241f647 postfix/local[264]: A2157A0084: to=<mail@mysite.com>, relay=local, delay=0.12, delays=0.1/0.01/0/0.01, dsn=2.0.0, status=sent (delivered to maildir)

This means that the mail is sent using local relay and i need to make it sent to external server/service that service the same domain.

Please.help me. If you need any additional info - let me know.

**Comment by MarvAmBass** [comment]
Hi Muzset,

that sounds like a general problem you might be able to fix with some really fancy postfix configuration.

In general I'd say that your postfix does everything like he's supposed to do.

Imagine:

- Your Postfix ist responsible for the Domain: `mysite.com`
    - `mailboxes@mysite.com` belongs to `mysite.com` and is therefore under control of your postfix

Maybe you're able to add some forwarding rule like:

_forward all mails comming to `mailboxes@mysite.com to mailboxes@(mx ip addr of mysite.com)`


I can't give you a good solution for such a odd szenario - but maybe you're able to find something in the postfix manual / configuration how to configure a postfix to only listen to a few specific mails and relay specific boxes of the same domain to a different mailserver
