### ISSUE TITLE
Set hostname separete from domain name

### ISSUE THREAD

**Issue by adbrv** [MarvAmBass/docker-versatile-postfix#15]
Set hostname separate from domain name. Is it possible? Maybe you have fast solution? 
Thank you.

**Comment by MarvAmBass** [comment]
as stated in my readme, you can use `POSTFIX_RAW_CONFIG_<POSTFIX_SETTING_NAME>` to configure/overwrite all postfix settings.

Is there a reason you want to specify the hostname?

**Comment by adbrv** [comment]
Yeah, we are trying to use image as second smtp server and we can't send mail normally from our domain because this domain have dns a record to web server. as we sending mail from another ip antispam filters cut our mail.

**Comment by MarvAmBass** [comment]
hi there,

ahhh now we're on the same page. that's the problem - this container is not meant to be used behind some other server in the background.

BUT: I have exactly what you want

I have to "mail-box" container which are meant to be used behind some mail gateway

https://github.com/ServerContainers/minimail (newest and lightweight)

https://github.com/ServerContainers/mail-box (debian based and if you want to go big with several tousand users)

and if you want a solid container doing your virus scanning, spam filtering etc you can take a look at this one

https://github.com/ServerContainers/mail-gateway
(used incoming gateway can filter and scan mail)
(used as outgoing gateway can alter headers and sign with dkim etc.)

**Comment by adbrv** [comment]
Thanks we will try this solutions!
