### ISSUE TITLE
Ubuntu version update? 

### ISSUE THREAD

**Issue by puzrin** [MarvAmBass/docker-versatile-postfix#16]
14.04 LTS standard support ended in 2019.

Probably worth switch to 18.04 or 20.04.

PS. Thanks for great config.

**Comment by MarvAmBass** [comment]
Hi there,

that's true - but this container kinda deprecated and just stays there for all existing users or users who want to build there own.

If you like to upgrade the server (maybe updating the FROM tag ist enough), test is and sent me a pull request, I might merge it.

other then that I moved on to a bit more sophisticated mail system containers

https://github.com/ServerContainers/minimail

in combination with 

https://github.com/ServerContainers/mail-gateway

those containers are still maintained and I try to keep them up to date and everything
