### ISSUE TITLE
Some POSTFIX_RAW_CONFIG parameters should not be lowercased

### ISSUE THREAD

**Issue by NotYourFox** [MarvAmBass/docker-versatile-postfix#18]
For instance, there is a TLS-related field named smtpd_tls_CAfile.
With all the names for POSTFIX_RAW_CONFIG_* being lowercased, it becomes impossible to set the field with something like ```-e POSTFIX_RAW_CONFIG_SMTPD_TLS_CAFILE```.

I guess making anything after POSTFIX_RAW_CONFIG_ case-sensitive would be a solution. Maybe add an option to actually make POSTFIX_RAW_CONFIG parameters case-sensitive for backwards compatibility?

**Comment by MarvAmBass** [comment]
done

**Comment by MarvAmBass** [comment]
image: `marvambass/versatile-postfix:2024`
