### ISSUE TITLE
Clarification around multiple domains, or configuration in general

### ISSUE THREAD

**Issue by jonkri** [MarvAmBass/docker-versatile-postfix#2]
Hi!

Thanks for a nice Docker image! :)

I was curious as to what would be a good approach to set up multiple domain names using this image. Should I volume in a Postfix configuration file, perhaps?

I think some pointers on this, or configuration in general, could be beneficial in the README file.

Cheers!

**Comment by MarvAmBass** [comment]
making this compatible to more domains would require a lot of small changes.

the best way for you would be to fork this project and make this a completly new project.

this should stay simple and only needs to work with one domain

**Comment by jonkri** [comment]
Thanks for the clarification!

Someone should perhaps rephrase "You can <strong>initially</strong> create one Domain" in the README file, as to make this clearer. :)
