### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by mpartipilo** [MarvAmBass/docker-versatile-postfix#7]
I am thinking of how to use a single postfix to serve multiple domains. I will try to come up with the required changes and do a PR.

**Comment by MarvAmBass** [comment]
Hi, well by now I always told contributors with this wish to fork my project and modify it to their needs. But if you implement it nicely I'm happy to merge it.

Thanks and greetings

Marvin

**Comment by mpartipilo** [comment]
I figured this could be done with a nginx plugin as a reverse proxy.

**Comment by MarvAmBass** [comment]
good idea, keeps the container logic simple and gives you flexibility 👍
