### ISSUE TITLE
Flag to disable TLS

### ISSUE THREAD

**Issue by mpartipilo** [MarvAmBass/docker-versatile-postfix#8]
I'm having trouble with the self-signed certificate.

```
# TLS parameters
#smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
#smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
#smtpd_use_tls=yes
#smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
#smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
```

**Comment by MarvAmBass** [comment]
can you be a bit more specific about your troubles with the cert, you can allways use official certificates like letsencrypt or similar

**Comment by MarvAmBass** [comment]
I consider this ticket invalid since it's against my approach of using plaintext connections.

**Comment by MarvAmBass** [comment]
maybe you can disable it with my newly added variable

`POSTFIX_RAW_CONFIG_` (look at the readme)
```
POSTFIX_RAW_CONFIG_smtpd_use_tls=no
```

might help you

**Comment by mpartipilo** [comment]
Thanks!

It looks useful. I like your stand on security, it has given me the inspiration I needed and I will try to secure it. Even if it’s a password protected forward and send-only server, it won’t hurt.

Michelangelo P.
