### ISSUE TITLE
I suggest new feature: add "debug" flag to log mail content, with header…

### ISSUE THREAD

**Issue by harobed** [MarvAmBass/docker-versatile-postfix#9]
I suggest new feature: add "debug" flag to log mail content, with header…

Tips:

Use:

```
RUN postconf -e content_filter="scan:localhost:10025"
```

**Comment by MarvAmBass** [comment]
what exactly do you want to achieve with that?

**Comment by MarvAmBass** [comment]
I just added `POSTFIX_RAW_CONFIG_ ` (look at updated README) to enable everyone to set thier own properties and overwrite mine

**Comment by harobed** [comment]
Thanks
